accumulated changes from Mac

diff --git a/opensh/gr b/opensh/gr
--- a/opensh/gr
+++ b/opensh/gr
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-#if [ $mtype = 90 ]; then
-#  gradle --no-daemon "$@"
-#else
-    if [ -r ./gradlew ]; then
-      exec ./gradlew --no-daemon "$@"
-    elif [ -r ../gradlew ]; then
-      exec ../gradlew --no-daemon "$@"
-    else
-      echo "can't find ./gradlew or ../gradlew"
-      exit 2
-    fi
-#fi
+if [ -r ./gradlew ]; then
+  exec ./gradlew --no-daemon "$@" -Dcomposite
+elif [ -r ../gradlew ]; then
+  exec ../gradlew --no-daemon "$@" -Dcomposite
+else
+  echo "can't find ./gradlew or ../gradlew"
+  exit 2
+fi
+
